### ISSUE TITLE
Test improvements 

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#10]
Currently our tests cover almost nothing. We need to unit test as much as possible 

https://github.com/blalor/hubot-mock-adapter

What you want to test - and do each of these independently:

* You extract messages from the channel(s)
  * You act on messages with an action and ignore those that don't
* You parse those messages to a correct structure
  * e.g. xxx @abc +todo => `{ .... }`
* You act on those messages in the right way e.g. you log to gist or doc
  * You parse and use the routing config correctly

You want to mock the code ...

* Connecting to the room and getting messages
* Mock out google docs or github API and check you get messages sent

Example using nock:

https://github.com/frictionlessdata/dpr-js/blob/gh-pages/tests/utils/datapackage.test.js

https://github.com/node-nock/nock

```
robot._saveToGoogleDoc(message)

mock(robot._saveToGoogleDoc, myStubFunction)
```

**Comment by weirdGuy** [comment]
We've been trying to build tests.
Failed cause there is couple problems, that we've faced:
1. Every function inside the messages.js always call some other API and all of them is connected via callback's so the returning data(to assert) is might be lost or not pushed to the proper callback.
2. For some services there is used a lot of api calls for urls, which also specify a lot of side parameters, so it's really hard to find which one should be mocked.

**Comment by weirdGuy** [comment]
FIXED.
Created new tests, refactored code
