### ISSUE TITLE
Script improvements 

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#11]
- why this script is called [example.coffee](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee)
- Not sure, but I think we don't need anything after [line 29](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L29) in example.coffee  maybe [line 60](https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L29) for tests?
- I see we are using ES6 for JS - Eg: `import` , `let` syntax. Can we stay consistent? Eg: use let / const instead of var as needed https://github.com/atomatichq/ourbot/blob/master/scripts/messages.js#L23 . Also use arrow functions where apropriate

**Comment by weirdGuy** [comment]
Fixed
