### ISSUE TITLE
add channel name to the spreadsheet

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#22]
currently we are documenting following info 
- action
- timestamp
- poster
- assignees
- message

We need to add `channel` column to know from which channel the message was sent

**Comment by weirdGuy** [comment]
FIXED.
Added channel name to spreadsheet

**Comment by zelima** [comment]
Is this really fixed, cause I don't actually see any info about channel name Eg in my gist  https://gist.github.com/datopianbot/2b2875c259f5c41ee8ad6c447bd99667

**Comment by weirdGuy** [comment]
FIXED.
