### ISSUE TITLE
Why is repo large (23 Mb) when we only have a few scripts ...

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ourbot#28]

**Comment by weirdGuy** [comment]
Somewhere in the past, there were heroku.tar.gz archive pushed

**Comment by rufuspollock** [comment]
@weirdGuy (cc @zelima) was that an accident / unneeded?

If so can we rebuild the repo history with this stripped out so we don't have to live with it for evermore :wink:

**Comment by zelima** [comment]
@weirdGuy can you show me that in history? paste the link to commit, I can not find one

**Comment by weirdGuy** [comment]
@rufuspollock @zelima it's from begining of this repo :) https://github.com/datopian/ourbot/tree/57b1eb78fe229f6ec7adb7b07940f08288eb994f

**Comment by zelima** [comment]
@weirdGuy is it now deleted? why I can not see it?

**Comment by weirdGuy** [comment]
@zelima yes, on some step i've deleted this file

**Comment by zelima** [comment]
@weirdGuy I think this is fixed now. 

Can you please update and close if needed

**Comment by weirdGuy** [comment]
FIXED.
Deleted ```heroku.tar.gz``` from all history
