### ISSUE TITLE
Naming our bot

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ourbot#36]
How does the bot name get set - both generally and in the channel?

How do we reference the bot or issue orders to the bot (e.g. do we need to prefix with the bot name or not)?

**Comment by Mikanebu** [comment]
FIXED in this issue: https://github.com/datopian/ourbot/issues/48

**Comment by rufuspollock** [comment]
@Mikanebu please can you close these issues with FIXED and a summary of the changes made e.g. this is how you rename ... and we renamed to ...

**Comment by Mikanebu** [comment]
FIXED, our bot name is changed from `ourbot` to `bot`.

**Comment by Mikanebu** [comment]
FIXED, our bot name changed from `outbot` to `bot`

**Comment by Mikanebu** [comment]
FIXED, our bot name is `bot`. I changed `Procfile` file, where we assign name for the bot by `--name bot`.  Before, it had `--name ourbot`. Then, republished on heroku
