### ISSUE TITLE
README is missing instructions for installation and tests

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#4]
We have a guide for getting google and gist API keys, but not simple instructions how to install app an run locally.

Eg:

### Setup

You'll need to install coffee-script to run the app and tests. To install follow here: ....

Install the app:
```
# clone the repo
git clone https://github.com/atomatichq/ourbot.git
cd ourbot
npm install
```
Run the tests
```
npm test
```

**Comment by weirdGuy** [comment]
9fcb453
Added to readme
