### ISSUE TITLE
Rename to bot on channel (rather than `datopianbot`)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ourbot#47]
And can we have aliasing support so it can have multiple names.

**Comment by Mikanebu** [comment]
`datopianbot` is the username on GitHub. We can change it from the settings. We already changed from `ourbot` to `bot` Or what do you mean by changing name?

**Comment by Mikanebu** [comment]
username `bot` has already taken

**Comment by rufuspollock** [comment]
@Mikanebu i mean the name the bot responds to in the channel (not the name of the user we add to the channel). I think we have already done this ... so we can close as FIXED.

**Comment by Mikanebu** [comment]
FIXED, now our hubot name is `bot` in the channel
