### ISSUE TITLE
Create github issue from gitter channel

### ISSUE THREAD

**Issue by Mikanebu** [datopian/ourbot#52]
We want to create issues by our bot.

## Acceptance criteria

* [x] `bot issue "+link function for recording links in gist" about "We want to test our bot issue create command" in "datopian/ourbot"` - will create an issue in `datopian/ourbot`

### 1st approach

* [x] get GitHub token to create an issue
* [x] create function `hear` in `main.js`
* [x] create separate script `createIssue.js`
* [x] write unittest
* [x] update `README.md`
* [x] test locally in `bot` channel
* [x] push to heroku

### 2nd approach

* [ ] npm install hubot-gh-issues
* [ ] npm install hubot-gh-token
* [ ] add to `external-scripts.json` the following properties:
```
[
  "hubot-gh-issues",
  "hubot-gh-token"
]
```
* [ ] set env.var `HUBOT_GITHUB_TOKEN_FERNET_SECRETS`
## Analysis 

There are 2 ways of creating issues using our bot. First one is using GitHub API call which has almost all the collection of API's in http://github-tools.github.io/github/docs/3.1.0. Second is using already written packages in `hubot` official page https://github.com/hubot-scripts/hubot-gh-issues. 

1) Make any call to the Github v3 API 
This is a Hubot-compatible Github API wrapper for Node.js:
https://github.com/iangreenleaf/githubot 
In addition, all the list of API calls can be found here, especially for `javascript`: 
http://github-tools.github.io/github/docs/3.1.0/Issue.html#createIssue
Command: `bot github open issue "+link function for recording links in gist" in "datopian/ourbot`
For any typing error or structure change, bot will not respond. 
In order to realise abovementioned code, we have to set up the following tasks/steps:
* Create new token with admin rights for GitHub
* Create new function in `main.js` to `hear` the abovementioned bot command
* Create new script `createIssue.js` which contains API call to create issue

2) Use already written scripts/packages in `hubot-script` official page:
https://github.com/hubot-scripts
GitHub issue
```
bot issue "everything is broken!" about "all of the things are broken, help!" in "somecompany/somerepo"
```
GitHub issue create:
https://github.com/hubot-scripts/hubot-gh-issues

Conclusion: Evaluation abovementioned 2 solutions, I will go with a 1st solution using API calls, since it has the library to support it and it is updated. 2nd solution is little weak, since the library was updated 9 months ago, and it has close to zero starts, which make it less reliable.

**Comment by zelima** [comment]
@Mikanebu one nice thing I noticed in the second approach is "about" section - You can create an issue and also provide some description. Think that is quite a nice feature. Can you accomplish same with the first approach?

@Mikanebu, to be honest, It is not quite clear why you choose approach number one. could you please provide more detailed pros and cons for both of them? What are main disadvantages for the second approach? the fact that it is not popular (has only two stars), bugs, other? 

my sense here is to go with an existing library, even though it has only two stars, think it is worth at least trying (unless you have good reason not to do so)

**Comment by Mikanebu** [comment]
@zelima ok, I will go with existing library, it should take no more that 1hour with tests. I thought that we have a create and a close milestone using API, so they all will be in the same logic.

**Comment by zelima** [comment]
@Mikanebu I do not force you to choose any of these options. That was just a suggestion. 

To follow same logic everywhere would be a good reason to stay with approach N1. (just please provide more detailed advantages and disadvantages in the analyses section)

**Comment by rufuspollock** [comment]
Suggest simple: `bot issue ....` (no github, no open etc)

**Comment by Mikanebu** [comment]
FIXED. I used 1st approach since I had to refactor command to remove `open github` words
