### ISSUE TITLE
Sensitive info should not directly set in config.json

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#7]
Currently to run bot we need to set all the g-docs configurations (that should not public) in `config.json` + gitter ID in Procfile for heroku.
To deploy application on heroku we need to run `git push heroku master` and  include `config.json` and Procfile filled in the commit. This means that all our sensitive data will be publicly available.

### solution

We should move all the sensitive variable into `.env` and load them from the script. Eg:
```
# .env

# AUTH
GOOGLE_PRIVATE_KEY="<long_private_key>",
GOOGLE_CLIENT_EMAIL="<key_email>",

GITHUB_...
```
So that we can set env variables for heroku later, by simply running `heroku configure:set SOME_VARIABLE=variable`

**Comment by rufuspollock** [comment]
@weirdGuy and for local dev you can have variables in a `.env` file.

**Comment by weirdGuy** [comment]
Fixed
