### ISSUE TITLE
Add configurable "docs" and "monitor" parameters to config.json

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#8]
Currently we are using only google docs for saving our logs and probably is hardcoded 
We need this to be configurable as there may be more places, where we may save our logs like gist etc... 

### [update]

Also we need to have configurable google sheet or gist id so we could Eg: save logs from different channels in different sheets. currently `GOOGLE_WORKSHEET` variable is set in `.env` file - meaning we can use only one spreed sheet to save logs. We may and we will need to have multiple of them 
So this variable should be set in `config.json`. (same with gist)
```
{
  docs: {
    "gist1": {
      "type": "gist"
      "url": ...
    }
    "gdocs1": {
      "type": "gdocs"
      "worksheet": GOOGLE_WORKSHEET
    }
  }
}
```

Also  we are using fixed "key words"  - `+todo` and `+standup` that are hard coded this into the script: https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L24
We need this to be configurable as well and set into `config.json` as there might be much more, or we may need to modify.

```
// config.json
{
  docs: {
    "gist1": {
      "type": "gist"
      "url": ...
    }
    "gdocs1": {
      "type": "gdocs"
      "worksheet": ...
    }
  }
  monitors: [
    {
      "room": "datopian/dev"
      "term": "+todo",
      "action"": "todolog",
      "doc": "gist1"
    },
    {
      "room": "datopian/dev",
      "term": "+standup",
      "action": "standuplog",
      "doc": "gdocs1"
    },
    ..
}
```

#### List of the helper functions functions to get needed info from configuration 
- [x] Parse: ... 
- [x] 2 loggers: todo and standup
  - [x] todo does nothing - passed through the structure
  - [x] standup: converts `{ ... }` to a string
- [x] 2 writers
  - [x] GDocs
  - [x] Gist - stringify what it is given and appends it ...

**Comment by zelima** [comment]
@weirdGuy what's the status here? Please close as FIXED if so

**Comment by weirdGuy** [comment]
FIXED.
config.json was configured and works properly
