### ISSUE TITLE
Add configurable "monitor" parameter to config.json

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#9]
Currently we are using fixed "key words"  - `+todo` and `+standup` that are hard coded this into the script: https://github.com/atomatichq/ourbot/blob/master/scripts/example.coffee#L24
We need this to be configurable as well and set into `config.json` as there might be much more, or we may need to modify.

```
{
  ...
  monitor: {
    "+todo": {
      "action"": "log",
      "dest": "gist1"
    },
    "+standup": ...
  }
}
```

**Comment by weirdGuy** [comment]
@zelima alright, this key words could be done in config, but hubot doesn't support array/object as the argument to monitor words, or we just can monitor every message and loop through our array/object to find where it should be stored, there's the question about perfomance

**Comment by zelima** [comment]
@weirdGuy or maybe we could do something like this (don't know coffee-script but):
```
keyWords = Object.values(config.motor) //get keys as list
for key in words
  do robot.hear key, (res) ->
      messages.sendMessage(res.message)
```

**Comment by weirdGuy** [comment]
@zelima reffering to the documentation(http://nick.balestra.ch/hackbot/robot.html#section-3) and also i have tried it now by myself -- its impossible, but will try another way of this

**Comment by weirdGuy** [comment]
@zelima the way it could be done in config, like this: 
```
"keys": "\\+todo|\\+standup/i"
```

**Comment by weirdGuy** [comment]
FIXED job is done here https://github.com/atomatichq/ourbot/pull/14
